//Auto-generated by UXL Compiler
//Source: web/views/FreeCellTemplate.uxl.xml

//1#
part of freecell;

/** Template, FreeCellTemplate, for creating views. */
List<View> FreeCellTemplate({View parent, cards}) { //5#
  List<View> _rv = new List(); View _this_;

  final _c0 = new MainController();
  final mainController = _c0;
  List<View> _c0T({View parent, View beforeChild}) { //6#
    List<View> _rva = new List(); View _this_;

    //6# <View layout="type: linear; orient:...>
    final _va0 = _this_ = (_c0.view == null ? _c0.view = new View(): new View())
      ..layout.text = '''type: linear; orient: horizontal; spacing: 0'''
      ..style.cssText = '''border: 1px solid #553; background-color: DarkGreen'''
      ..profile.text = '''width: flex; height: flex''';
    if (parent != null)
      parent.addChild(_va0, beforeChild);
    _rva.add(_va0);

    //11# <View layout="type: linear; orient:...>
    final _va0_0 = _this_ = new View()
      ..layout.text = '''type: linear; orient: vertical; spacing: 0'''
      ..style.cssText = '''border: 1px solid #553; background-color: DarkSeaGreen;   '''
      ..profile.text = '''width: 9%; height:flex''';
    _va0.addChild(_va0_0);

    //16# <View layout="type: linear; orient:...>
    final _va0_1 = _this_ = new View()
      ..layout.text = '''type: linear; orient: vertical; spacing: 0'''
      ..style.cssText = '''border: 1px solid #553; background-color: DarkKhaki;   '''
      ..profile.text = '''width: 2%; height:flex''';
    _va0.addChild(_va0_1);

    for (var r = 0; r < 8; r++) {

      //23# <View layout="type: linear; orient:...>
      final _va0_2 = _this_ = new View()
        ..layout.text = '''type: linear; orient: vertical; '''
        ..style.cssText = '''border: 1px solid #553; background-color: DarkGreen;'''
        ..profile.text = '''width: 9%; height:flex''';
      _va0.addChild(_va0_2);

      for (var c = 0; c < 7; c++) {

        if (mainController.card(cards,r,c) != null) {

          //28# <Panel layout="type: linear;  " styl...>
          final _va0_2_0 = _this_ = new Panel()
            ..layout.text = '''type: linear;  '''
            ..style.cssText = '''background-color: DarkGreen'''
            ..profile.text = '''width: 100%''';
          _va0_2.addChild(_va0_2_0);

          //32# <Image src="${mainController.card(ca...>
          final _va0_2_0_0 = _this_ = new Image()
            ..src = mainController.card(cards,r,c)
            ..style.cssText = '''width: 80%; height: 100%; margin-left: 20%; ''';
          _va0_2_0.addChild(_va0_2_0_0);
        }
      }

      if (r < 7) {

        //39# <View if="r < 7" layout="type: linea...>
        final _va0_3 = _this_ = new View()
          ..layout.text = '''type: linear; orient: vertical; spacing: 0'''
          ..style.cssText = '''border: 1px solid #553; background-color: DarkKhaki;   '''
          ..profile.text = '''width: 1%; height:flex''';
        _va0.addChild(_va0_3);
      }
    }

    //47# <View layout="type: linear; orient:...>
    final _va0_4 = _this_ = new View()
      ..layout.text = '''type: linear; orient: vertical; spacing: 0'''
      ..style.cssText = '''border: 1px solid #553; background-color: DarkKhaki;   '''
      ..profile.text = '''width: 2%; height:flex''';
    _va0.addChild(_va0_4);

    //52# <View layout="type: linear; orient:...>
    final _va0_5 = _this_ = new View()
      ..layout.text = '''type: linear; orient: vertical; spacing: 0'''
      ..style.cssText = '''border: 1px solid #553; background-color: DarkSeaGreen;   '''
      ..profile.text = '''width: 8%; height:flex''';
    _va0.addChild(_va0_5);
    return _rva;
  }
  _c0.template = _c0T;
  final _v0 = _c0T(parent: parent)[0];
  _rv.add(_v0);
  _c0.onRender();
  return _rv;
}
